# Generated by Django 2.2.6 on 2019-10-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191019_0541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergamelevelmodel',
            options={'ordering': ['game_level__level_number', 'user_game_module']},
        ),
        migrations.AlterModelOptions(
            name='usergamemodulemodel',
            options={'ordering': ['game_module__module_number']},
        ),
        migrations.AddField(
            model_name='gamelevelmodel',
            name='level_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamemodulemodel',
            name='module_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
