# Generated by Django 2.2.6 on 2019-11-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191026_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelevelmodel',
            name='blocks',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamelevelmodel',
            name='prompt',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
