# Generated by Django 2.2.7 on 2019-11-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191108_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelevelmodel',
            name='inputs',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
