# Generated by Django 2.2.7 on 2019-11-10 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_gamelevelmodel_inputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelevelmodel',
            name='list_input_site',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamelevelmodel',
            name='num_inputs',
            field=models.IntegerField(default=0),
        ),
    ]
