# Generated by Django 2.2.7 on 2019-12-04 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelevelmodel',
            old_name='list_input_site',
            new_name='list_input_size',
        ),
    ]
